server:
  port: 8123
spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xxx/zoupicture
    username: zoupicture
    password: xxx
  #redis配置
  redis:
    database: 0
    host: xxx
    port: 6379
    timeout: 5000
    password: xxx
  #分布式锁+限流
  redisson:
    single-server:
      address: redis://xxx
      password: xxx
      database: 0
      timeout: 3000
    # rabbitmq 信息
  rabbitmq:
    host: xxx
    password: xxx
    username: xxx
    port: 5672             #5672默认是RabbitMQ的web端管理平台的端口；5672是MQ访问的端口


mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''

# 接口文档配置
knife4j:
  basic:
    enable: true
    username: root
    password: 123456

# 对象存储配置（需要从腾讯云获取）
cos:
  client:
    host: xxx   #域名
    secretId: xxx
    secretKey: xxx
    region: xxx
    bucket: xxx               #存储桶名称


# 阿里云 AI 配置
aliYunAi:
  apiKey: xxx